name: setup-npm-bs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
          cache-dependency-path: ./sub/yarn.lock

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: "npm"
          cache-dependency-path: sub/package-lock.json
          
      - name: Run a multi-line script
        run: |
          node --version
          yarn install
          node main.js
        working-directory: sub
